import {test} from 'node:test';
import assert from 'node:assert/strict';
import {packQuantity,catalogValue} from '../src/pack-catalog.js';
test('official quantities preserve K and M multipliers',()=>{assert.equal(packQuantity('2.5K'),2500);assert.equal(packQuantity('1.8M'),1800000);assert.equal(packQuantity('bad'),null);});
test('diamond denominations count face value; unpriced items prevent ranking',()=>{const pack={contents:[{id:'200367',quantity:'1'},{id:'230109',quantity:'900'}]};const v=catalogValue(pack,{},5000);assert.equal(v.gems,5000);assert.equal(v.missing,1);assert.equal(v.ratio,null);const full=catalogValue(pack,{'230109':20},5000);assert.equal(full.gems,23000);assert.equal(full.ratio,4.6);});
test('blank price is unknown, explicit zero is allowed',()=>{const p={contents:[{id:'230109',quantity:'1'}]};assert.equal(catalogValue(p,{'230109':''},1).complete,false);assert.equal(catalogValue(p,{'230109':0},1).complete,true);});
import catalog from '../src/pack-catalog.json' with {type:'json'};
test('screenshot partial packs cannot become full rankings even with all prices entered',()=>{const pack=catalog.packs.find(p=>p.id==='screen-alloy');const v=catalogValue(pack);assert.ok(v.gems>69000);assert.equal(v.complete,false);assert.equal(v.ratio,null);assert.ok(v.knownRatio>34);});
test('diamond first-purchase bonus is opt-in and does not change gold cost',()=>{const p=catalog.packs.find(p=>p.id==='diamonds-500');assert.equal(catalogValue(p).gems,500);assert.equal(catalogValue(p,{},undefined,true).gems,1000);assert.equal(catalogValue(p).ratio,500/499);});
test('screenshot and official packs keep separate costs and content lists',()=>{assert.equal(catalog.packs.find(p=>p.id==='screen-core').goldBars,4999);assert.equal(catalog.packs.find(p=>p.id==='777772003').goldBars,undefined);});
test('weekly diamond pass counts immediate gems once and daily claims separately',()=>{const p=catalog.packs.find(p=>p.id==='pass-diamonds');assert.equal(catalogValue(p).gems,2600);assert.equal(catalogValue(p,{},undefined,false,0).gems,500);assert.equal(catalogValue(p,{},undefined,false,3).gems,1400);assert.equal(catalogValue(p,{},undefined,false,99).gems,2600);});
test('all predefined pack lines resolve to known items',()=>{for(const p of catalog.packs)for(const l of p.contents)assert.ok(catalog.items[l.id],`${p.id}: ${l.id}`);});
