import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {effectiveSeconds,parseScreens,windows,recommend} from '../src/planner.js';
const catalog=JSON.parse(readFileSync(new URL('../public/buildings.json',import.meta.url))).upgrades;
test('isolated building card pairs the level above its name',()=>{
 const result=parseScreens('Lv.26\nHeadquarters',['Headquarters'],1,35,{isolatedCard:true});
 assert.equal(result.buildings[0].level,26);
});
test('game labels with a single OCR character error are offered for review, without guessing unknown levels',()=>{const result=parseScreens('RidepCamp)\nLv.25 -> Lv.26\nLaboratory upgrading...\nConstruction Speed Up 255.70%', ['Rider Camp','Laboratory']);assert.equal(result.buildings[0].name,'Rider Camp');assert.equal(result.buildings[0].level,25);assert.equal(result.buildings[1].active,true);assert.equal(result.speed,255.7);const unknown=parseScreens('Laboratory upgrading...',['Laboratory']);assert.equal(unknown.buildings[0].level,null);});
test('screenshot-supported construction bonus divides the base duration',()=>{assert.ok(Math.abs(effectiveSeconds(3186963,255.70)-895969)<=1);assert.throws(()=>effectiveSeconds(10,-100));});
test('adjacent building levels are not taken from the previous building',()=>{const data=parseScreens('Headquarters Lv.26\nLaboratory Lv.25 upgrading\nCity Walls Lv.24\nConstruction Speed 255.70%', ['Headquarters','Laboratory','City Walls']);assert.deepEqual(data.buildings.map(b=>b.level),[26,25,24]);assert.equal(data.speed,255.7);assert.equal(data.buildings[1].active,true);});
test('Tuesday and Friday shelter blocks overlap, and UTC rollover is correct',()=>{const rows=windows(new Date('2026-10-06T01:00:00Z'),-120,7);assert.equal(rows[0].duel,'Vehicle');const match=rows.find(r=>r.overlap);assert.equal(new Date(match.start).toISOString(),'2026-10-06T10:00:00.000Z');assert.equal(match.duel,'Shelter');assert.ok(rows.some(r=>r.duel==='Balanced'&&r.theme==='Shelter'&&r.overlap));});
test('HQ dependencies lead the plan, active buildings are excluded, and unknown requirements are flagged',()=>{const b=[{id:'hq',name:'Headquarters',level:26},{id:'lab',name:'Laboratory',level:25},{id:'walls',name:'City Walls',level:25},{id:'camp',name:'Rider Camp',level:25,active:true}];const rows=recommend(b,catalog,255.7,new Date('2026-10-05T12:00:00Z'));assert.ok(['Laboratory','City Walls'].includes(rows[0].building));assert.equal(rows.some(r=>r.building==='Rider Camp'),false);assert.equal(rows.find(r=>r.building==='Headquarters').missing.length,2);for(const r of rows){assert.ok(r.completeAt>=r.finish);assert.equal(r.speedups,0);assert.ok(r.completeAt<r.window.end);}});
test('speedup budget is respected without applying speed twice',()=>{const rows=recommend([{id:'camp',name:'Rider Camp',level:25}],catalog,255.7,new Date('2026-10-05T12:00:00Z'),-120,5000);assert.ok(rows[0].speedups<=5000);assert.ok(rows[0].startAt>=Date.parse('2026-10-05T12:00:00Z'));});
