import './style.css';
import {createWorker} from 'tesseract.js';
import {duel,windows,duration,parseScreens,recommend} from './planner.js';
import config from '../public/config.json';
const $=id=>document.getElementById(id), escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let catalog=[],names=[],buildings=[],results=[],previews=[],busy=false,step=1;
let draft={name:'',speed:0,speedups:0,offset:-120};
try{Object.assign(draft,JSON.parse(localStorage.getItem('lastz-draft')||'{}'));buildings=Array.isArray(draft.buildings)?draft.buildings:[];}catch{}
const date=n=>new Date(n).toLocaleString(undefined,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
const time=n=>new Date(n).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'});
function persist(){try{localStorage.setItem('lastz-draft',JSON.stringify({...draft,buildings}));}catch{$('status').textContent='Your browser cannot remember this draft. You can still submit your plan.';}}
function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
$('app').innerHTML=`<header><div><div class="brand"><span class="mark">LZ</span><div>Alliance Planner<small>LAST Z · SURVIVAL SHOOTER</small></div></div><span class="private">A clearer plan. A stronger alliance.</span></div></header>
<main><div class="intro"><div><div class="eyebrow">Your next upgrade, timed well</div><h1>Make your upgrades count.</h1><p>Add your screenshots. We’ll help you plan around alliance events.</p></div><div class="today" id="today"></div></div>
<div class="steps" aria-label="Planning steps"><div class="step current" id="step1"><span>1</span>Add screenshots</div><div class="step" id="step2"><span>2</span>Check your buildings</div><div class="step" id="step3"><span>3</span>See your plan</div></div>
<div class="columns"><section><div class="card" id="intake"><div class="cardhead"><h2>Your base</h2><span class="badge">No account needed</span></div><p>Use screenshots of your building list or upgrade screens. Clear English text works best.</p>
<label class="upload"><svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><rect x="4" y="9" width="24" height="19" rx="3" stroke-width="2"/><path d="M16 21V3m-6 6 6-6 6 6" stroke-width="2"/></svg><strong>Add your screenshots</strong><span class="muted">Choose up to 8 images from your phone or computer</span><input id="screens" type="file" accept="image/png,image/jpeg,image/webp,image/bmp" multiple></label><div class="previews" id="previews"></div><progress id="progress" max="1" value="0" hidden></progress><div id="status" role="status" aria-live="polite"></div>
<div class="fields"><label>In-game name<input id="name" maxlength="60" placeholder="So leaders know whose plan this is" value="${escape(draft.name)}"></label><label>Construction speed (%)<input id="speed" type="number" min="0" max="5000" step="0.01" value="${Number(draft.speed)||0}"><small>Enter the total bonus, for example 255.70.</small></label></div>
<div class="actions"><button id="read" class="primary" disabled>Read screenshots</button><button id="manual">Enter buildings myself</button></div><p class="muted">Screenshots are read on your device. Only your confirmed buildings and plan are submitted to leaders.</p></div>
<div class="card" id="review" hidden><div class="cardhead"><h2>Check your buildings</h2><span class="badge">You’re in control</span></div><p>Check the names and current levels. Screenshot reading can miss things.</p><div id="building-list"></div><button id="add" class="textbutton">+ Add another building</button><details><summary>Timing options</summary><div class="fields"><label>Construction + universal speedups (minutes)<input id="speedups" type="number" min="0" max="10000000" value="${Number(draft.speedups)||0}"><small>Optional. These are a budget, not an instruction to spend.</small></label><label>Game clock UTC offset<select id="offset"><option value="-120">UTC −02:00 (alliance default)</option><option value="0">UTC +00:00</option><option value="120">UTC +02:00</option></select><small>Compare the game clock with UTC if your server differs.</small></label></div></details><div class="actions"><button id="plan" class="lime">Show my plan</button><button id="back">Back to screenshots</button></div></div>
<div class="card" id="plan-card" hidden><div class="cardhead"><h2>Your upgrade plan</h2><button id="edit" class="textbutton">Edit buildings</button></div><p id="plan-summary"></p><div class="notice">Building times and requirements are community estimates. Event times use the alliance’s recurring schedule; check current scoring in the game before spending.</div><div id="recommendations"></div><div class="actions"><button id="submit" class="primary">Submit to alliance leaders</button><button id="copy">Copy my plan</button></div><div id="submit-status" role="status" aria-live="polite"></div></div></section>
<aside><div class="card"><div class="cardhead"><h2>Event planner</h2><span class="badge">Your local time</span></div><p class="muted" id="timezone"></p><div id="events"></div><details><summary>This week’s Alliance Duel</summary><div class="week" id="week"></div></details><div class="notice">Tuesday: construction focus.<br>Friday: balanced growth.<br>Look for a Shelter window on the same day.</div><p class="muted">Future windows follow the community calendar. Server changes and scoring rules need in-game confirmation.</p><details><summary>Where these estimates come from</summary><p class="muted">Construction speed uses base time ÷ (1 + bonus / 100). Running timers already include bonuses.</p><p class="muted">UTC −02:00 was observed on the alliance game clock on October 1, 2026. Recurring Full Preparedness themes use the community baseline.</p><a href="https://wild-hoggs.com/tools/building/" target="_blank" rel="noopener">Building data</a> · <a href="https://lastz.gg/guides/full-preparedness" target="_blank" rel="noopener">Event calendar</a></details></div></aside></div></main>
<footer><span>Last Z Alliance Planner · Unofficial fan tool</span><button id="leader-open" class="textbutton">Alliance access</button></footer>
<dialog id="leader-dialog"><h2>Alliance leader access</h2><p>Enter your leader key to view submitted plans.</p><label>Leader key<input id="leader-key" type="password" autocomplete="off"></label><div class="actions"><button id="leader-login" class="primary">View alliance plans</button><button id="leader-close">Close</button></div><div id="leader-status" role="status"></div><div id="leader-plans"></div></dialog>`;
function showStep(n){step=n;for(let i=1;i<=3;i++)$(`step${i}`).classList.toggle('current',i===n);$('review').hidden=n!==2;$('plan-card').hidden=n!==3;$('intake').hidden=n===3;}
function renderBuildings(){
 $('building-list').innerHTML=buildings.length?buildings.map(b=>`<div class="building" data-id="${escape(b.id)}"><label>Building<select data-field="name">${names.map(n=>`<option ${n===b.name?'selected':''}>${escape(n)}</option>`).join('')}</select></label><label>Level<input data-field="level" aria-label="Level for ${escape(b.name)}" type="number" min="1" max="35" value="${b.level??''}" placeholder="?"></label><button class="delete" aria-label="Remove ${escape(b.name)}" data-remove="${escape(b.id)}">×</button><label class="active"><input type="checkbox" data-field="active" ${b.active?'checked':''}>Already upgrading (skip this building)</label></div>`).join(''):'<p class="empty">No readable buildings yet. Add a building below.</p>';
}
function renderEvents(){const list=windows(new Date(),draft.offset,3);const current=list[0];$('today').innerHTML=`<small>ALLIANCE DUEL TODAY</small><strong>${current.duel==='Shelter'?'Shelter · Construction':current.duel}</strong><small>Next reset ${time(list.find(w=>w.duel!==current.duel)?.start||current.end)}</small>`;$('timezone').textContent=Intl.DateTimeFormat().resolvedOptions().timeZone.replaceAll('_',' ');$('events').innerHTML=list.slice(0,4).map((w,i)=>`<div class="eventrow"><div class="time">${time(w.start)}<br>${time(w.end)}</div><div><strong>${w.theme}</strong><small>${new Date(w.start).toLocaleDateString(undefined,{weekday:'short'})}${w.overlap?' · Construction overlap':''}</small></div>${i===0?'<span class="live">Now</span>':''}</div>`).join('');$('week').innerHTML=duel.map((x,i)=>`<div class="day ${[1,4].includes(i)?'highlight':''}">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}<strong>${x}</strong></div>`).join('');}
function saveInputs(){draft.name=$('name').value.trim();draft.speed=Number($('speed').value);draft.speedups=Number($('speedups').value);draft.offset=Number($('offset').value);persist();renderEvents();}
function planText(){return [`Last Z plan — ${draft.name||'Member'}`,`Construction bonus: ${draft.speed}%`,...results.slice(0,4).map(r=>`${r.building} ${r.from_level} → ${r.to_level}: ${duration(r.seconds)}. ${r.missing.length?'Check prerequisites: '+r.missing.map(p=>p.building+' '+p.level).join(', '):r.startAt?'Start '+date(r.startAt)+', target finish '+date(r.completeAt)+'. Estimated speedups: '+r.speedups+'m.':'No suitable event window.'}`),'Estimates only; confirm costs and scoring in game.'].join('\n');}
function makePlan(){
 document.querySelectorAll('#building-list [data-id]').forEach(row=>{const b=buildings.find(x=>x.id===row.dataset.id);if(b){b.name=row.querySelector('[data-field="name"]').value;b.level=Number(row.querySelector('[data-field="level"]').value);b.active=row.querySelector('[data-field="active"]').checked;}});
 saveInputs();if(!$('speed').checkValidity()||!$('speedups').checkValidity()){status('Enter a valid speed bonus and speedup budget.',true);showStep(2);return;}
 if(!buildings.length||buildings.some(b=>!names.includes(b.name)||!Number.isInteger(b.level)||b.level<1||b.level>35)){status('Add a building and check that levels are whole numbers from 1 to 35.',true);return;}
 results=recommend(buildings,catalog,draft.speed,new Date(),draft.offset,draft.speedups);showStep(3);$('plan-summary').textContent=`${buildings.length} building${buildings.length===1?'':'s'} checked · ${draft.speed}% construction bonus`;
 $('recommendations').innerHTML=results.length?results.slice(0,4).map((r,i)=>`<article class="recommendation ${i===0?'first':''}"><div class="rank">${r.priority===0?'HQ prerequisite':r.building==='Headquarters'?'Next headquarters level':'Upgrade option'} · Estimate</div><h3>${escape(r.building)} <span class="muted">${r.from_level} → ${r.to_level}</span></h3><p>${duration(r.seconds)} with your current speed bonus.</p>${r.missing.length?`<div class="notice">Check these first: ${r.missing.map(p=>`${escape(p.building)} Lv. ${p.level}`).join(', ')}. Missing buildings are treated as unknown. Timing below is a scenario after requirements are met.</div>`:''}${r.startAt?`<div class="timing"><div><small>Suggested start</small><strong>${date(r.startAt)}</strong></div><div><small>Target finish · ${escape(r.window.duel)} + Shelter</small><strong>${date(r.completeAt)}</strong></div></div><p class="muted">${r.speedups?`Needs about ${r.speedups.toLocaleString()} minutes of speedups from your budget.`:'Times the natural finish for the event window.'} Assumes a free builder and no changes to your speed bonus.</p>`:'<p>No construction overlap found.</p>'}<details><summary>Estimated resources & requirements</summary><p class="resources">${Object.entries(r.costs).map(([k,v])=>`${escape(k)}: ${v===null?'unknown':Number(v).toLocaleString()}`).join(' · ')}</p><p class="muted">${r.prerequisites.map(p=>`${escape(p.building)} Lv. ${p.level}`).join(', ')||'No requirements listed in the community table.'}</p><a href="${escape(r.source_url)}" target="_blank" rel="noopener">View building source</a></details></article>`).join(''):'<p class="empty">No next upgrade found. Buildings already upgrading are skipped, and the database covers levels up to 35.</p>';
 $('submit-status').textContent='';persist();$('plan-card').scrollIntoView({behavior:'smooth',block:'start'});
}
$('building-list').addEventListener('change',e=>{const row=e.target.closest('[data-id]'),b=buildings.find(x=>x.id===row?.dataset.id);if(!b)return;const key=e.target.dataset.field;if(key)b[key]=key==='active'?e.target.checked:key==='level'?Number(e.target.value):e.target.value;persist();});
$('building-list').addEventListener('click',e=>{const id=e.target.dataset.remove;if(id){buildings=buildings.filter(b=>b.id!==id);renderBuildings();persist();}});
$('add').onclick=()=>{buildings.push({id:crypto.randomUUID(),name:'Headquarters',level:1,active:false});renderBuildings();persist();};
$('manual').onclick=()=>{showStep(2);renderBuildings();};$('back').onclick=()=>showStep(1);$('edit').onclick=()=>{showStep(2);renderBuildings();};$('plan').onclick=makePlan;
for(const id of ['name','speed','speedups','offset'])$(id).addEventListener('change',saveInputs);$('offset').value=String(draft.offset);
$('screens').onchange=()=>{previews.forEach(u=>URL.revokeObjectURL(u));previews=[];const files=[...$('screens').files];if(files.length>8||files.some(f=>f.size>12*1024*1024||!['image/png','image/jpeg','image/webp','image/bmp'].includes(f.type))){status('Choose up to 8 PNG, JPG, WebP or BMP images, under 12 MB each.',true);$('read').disabled=true;return;}previews=files.map(f=>URL.createObjectURL(f));$('previews').innerHTML=previews.map(u=>`<img class="preview" src="${u}" alt="Selected game screenshot">`).join('');$('read').disabled=!files.length;status(files.length?`${files.length} screenshot${files.length===1?'':'s'} ready to read.`:'');};
$('read').onclick=async()=>{
 if(busy)return;busy=true;$('read').disabled=true;$('manual').disabled=true;$('screens').disabled=true;$('progress').hidden=false;
 let worker;try{let current=0;worker=await createWorker('eng',1,{workerPath:new URL('../vendor/worker.min.js',import.meta.url).href,corePath:new URL('../vendor/core/',import.meta.url).href,langPath:new URL('../vendor/lang/',import.meta.url).href,logger:m=>{if(m.status==='recognizing text'){status(`Reading screenshot ${current+1} of ${$('screens').files.length}…`);$('progress').value=m.progress;}}});
  let all=[];for(const file of $('screens').files){const recognized=await worker.recognize(file);const parsed=parseScreens(recognized.data.text,names);all.push(...parsed.buildings);if(parsed.speed!==null){draft.speed=parsed.speed;$('speed').value=String(parsed.speed);}current++;}
  // Keep separate instances. Never silently overwrite a player's prior buildings.
  if(all.length)buildings.push(...all);showStep(2);renderBuildings();persist();status(all.length?`Found ${all.length} possible buildings. Check every name and level below.`:'Couldn’t read building names and levels. You can enter them below.',!all.length);
 }catch{showStep(2);renderBuildings();status('Screenshot reading couldn’t finish. Try clearer screenshots or enter your buildings below.',true);}finally{if(worker)await worker.terminate();busy=false;$('read').disabled=!$('screens').files.length;$('manual').disabled=false;$('screens').disabled=false;$('progress').hidden=true;}
};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(planText());$('submit-status').textContent='Plan copied. You can paste it into alliance chat.';}catch{$('submit-status').textContent='Copy is unavailable in this browser.';}};
async function api(path,options={}){if(!config.apiBase)throw Error('Alliance sharing is not connected yet. Your plan is still available here.');const response=await fetch(config.apiBase+path,options);const data=await response.json();if(!response.ok)throw Error(data.error||'Could not connect. Try again.');return data;}
$('submit').onclick=async()=>{if(!draft.name){$('submit-status').textContent='Enter your in-game name first. Tap Edit buildings to update it.';return;}$('submit').disabled=true;try{
 let token=localStorage.getItem('lastz-member-token');if(!token){token=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');localStorage.setItem('lastz-member-token',token);}
 await api('/api/plans',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({name:draft.name,speed:draft.speed,buildings:buildings.map(b=>({name:b.name,level:b.level,active:b.active})),summary:planText()})});$('submit-status').textContent='Submitted. Alliance leaders can now see your plan. Submit again to update it.';
 }catch(e){$('submit-status').textContent=e.message;}finally{$('submit').disabled=false;}};
$('leader-open').onclick=()=>$('leader-dialog').showModal();$('leader-close').onclick=()=>{$('leader-dialog').close();$('leader-key').value='';$('leader-plans').textContent='';};
$('leader-login').onclick=async()=>{$('leader-login').disabled=true;try{const data=await api('/api/plans',{headers:{'Authorization':'Bearer '+$('leader-key').value}});$('leader-status').textContent=`${data.plans.length} submitted plans`;$('leader-plans').innerHTML=data.plans.length?data.plans.map(p=>`<article class="leaderplan"><h3>${escape(p.name)}</h3><p class="muted">Updated ${date(p.updated_at)}</p><p>${escape(p.summary).replaceAll('\n','<br>')}</p></article>`).join(''):'<p>No member plans yet.</p>';}catch(e){$('leader-status').textContent=e.message;$('leader-plans').textContent='';}finally{$('leader-login').disabled=false;}};
try{const response=await fetch(new URL('../buildings.json',import.meta.url));if(!response.ok)throw Error();catalog=(await response.json()).upgrades;names=[...new Set(catalog.map(r=>r.building))].sort();renderBuildings();if(buildings.length)showStep(2);}catch{status('Building data could not load. Refresh the page to try again.',true);$('manual').disabled=true;$('plan').disabled=true;}
renderEvents();setInterval(renderEvents,60000);
