const assets={speed:'warehouse-speedups.jpg',resources:'warehouse-resources.jpg',equipment:'warehouse-equipment.jpg',hero:'warehouse-hero.jpg',items:'warehouse-items.jpg'};
// Coordinates are percentages of the original 589 x 1280 screenshots.
const rect=(x,y,w,h,label)=>({x:x/589*100,y:y/1280*100,w:w/589*100,h:h/1280*100,label});
export const guides={
 Shelter:{title:'Construction speedups',asset:'speed',regions:[rect(27,642,397,122,'Construction speedups: hammer icons'),rect(27,227,397,122,'Universal speedups: plain arrows')],note:'Save hammer speedups for a construction Full Preparedness + Alliance Duel overlap. Plain arrows are universal; reserve them for your chosen goal. The quantities shown here belong to the example account.'},
 Science:{title:'Research speedups',asset:'speed',regions:[rect(166,504,397,121,'Research speedups: flask icons'),rect(27,227,397,122,'Universal speedups: plain arrows')],note:'Save flask speedups for a research Full Preparedness + Alliance Duel overlap. Confirm the research is eligible for the current event before finishing it.'},
 Troops:{title:'Training speedups',asset:'speed',regions:[rect(443,227,121,122,'Training speedups: helmet icon'),rect(27,365,397,122,'More training speedups: helmet icons')],note:'Helmet icons are training speedups. Spend them only in a training Full Preparedness + Alliance Duel overlap; natural training needs no speedups. Green cross icons are healing speedups; keep them separate from training.'},
 Heroes:{title:'Hero Duel items',asset:'hero',regions:[rect(27,227,397,122,'Hero books: check the item tooltip'),rect(27,365,397,122,'Universal hero shards'),rect(27,504,537,542,'Shards for individual heroes')],note:'These books and shards are not Hero EXP. Save them for their eligible Alliance Duel tasks. Use Hero EXP on the hero level-up screen during Heroes Full Preparedness.'},
 Vehicle:{title:'Vehicle item candidates',asset:'items',regions:[rect(304,748,120,118,'Wrench item: confirm its name and purpose'),rect(27,887,120,118,'Blueprint item: confirm its name and purpose')],note:'Save eligible vehicle materials for a vehicle Full Preparedness + Alliance Duel overlap. These are visual candidates, not confirmed item identities. Tap each icon in-game and confirm the name and event eligibility before spending.'},
 equipment:{title:'Hero equipment',asset:'equipment',regions:[rect(27,227,259,122,'Equipment materials: open the item details'),rect(304,227,260,122,'Equipment and its displayed level')],note:'Check the exact equipment material requirements in-game. Equipment upgrades may not score in every Heroes event.'},
 resources:{title:'Resource supplies',asset:'resources',regions:[rect(27,227,537,398,'Resource chests'),rect(27,642,537,257,'Resource packs and their quantities')],note:'Resources pay upgrade costs. Opening packs is not assumed to earn event points. Open only what your confirmed upgrade needs; chest contents must be checked in-game.'}
};
export function mountInventoryGuide(container){
 let selected='';
 function show(key){if(selected===key)return;selected=key;const guide=guides[key]||guides.Shelter;
 container.innerHTML=`<details open><summary>See item examples</summary><p class="muted">Highlighted on your alliance's example screenshots. Your inventory and quantities will be different.</p><div class="inventory-tabs">${Object.entries(guides).map(([k,g])=>`<button data-guide="${k}" aria-pressed="${k===key}">${g.title}</button>`).join('')}</div><div class="inventory-guide"><figure><div class="inventory-image"><img src="./examples/${assets[guide.asset]}" alt="Warehouse ${guide.asset} screenshot with numbered highlights for ${guide.title}" width="589" height="1280" loading="lazy">${guide.regions.map((r,i)=>`<span class="inventory-highlight" style="left:${r.x}%;top:${r.y}%;width:${r.w}%;height:${r.h}%" aria-hidden="true"><b>${i+1}</b></span>`).join('')}</div></figure><div><h3>${guide.title}</h3><ol>${guide.regions.map(r=>`<li>${r.label}</li>`).join('')}</ol><p>${guide.note}</p><a href="./examples/${assets[guide.asset]}" target="_blank" rel="noopener">Open original screenshot</a></div></div></details>`;
 }
 container.onclick=e=>{const key=e.target.dataset.guide;if(key)show(key);};
 show('Shelter');return {show};
}
