import catalog from './pack-catalog.json' with {type:'json'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function packQuantity(v){const match=String(v).match(/^(\d+(?:\.\d+)?)([KM]?)$/i);return match?Number(match[1])*({K:1000,M:1000000}[match[2].toUpperCase()]||1):null;}
export function catalogValue(pack,prices={},cost){let gems=0,missing=0;const lines=pack.contents.map(l=>{const rate=catalog.items[l.id].gems??prices[l.id],quantity=packQuantity(l.quantity);const valid=rate!==''&&rate!=null&&Number.isFinite(Number(rate))&&Number(rate)>=0&&quantity!==null;if(!valid)missing++;const value=valid?quantity*Number(rate):null;if(value!==null)gems+=value;return {...l,value};});const complete=missing===0&&Number(cost)>0&&Number.isFinite(Number(cost));return {gems,missing,lines,complete,ratio:complete?gems/Number(cost):null};}
export function mountPackCatalog(container){
 container.oninput=null;container.onchange=null;container.onclick=null;
 let saved={prices:{},costs:{}};try{const x=JSON.parse(localStorage.getItem('lastz-pack-catalog'));if(x?.prices&&x?.costs)saved=x;}catch{}
 const fmt=n=>n.toLocaleString(undefined,{maximumFractionDigits:2});
 const image=id=>`<img src="${(import.meta.env?.BASE_URL??'/')}pack-items/${id}.png" alt="" loading="lazy" width="48" height="48">`;
 container.innerHTML=`<h2>In-game packs</h2><p>Choose a pack to see its contents and gem value.</p><p class="hint">Official store snapshot · ${catalog.checked}. Shop gem prices and gold-bar costs still need verification. Incomplete packs show known value only.</p><div class="pack-offers">${catalog.packs.map(p=>`<article class="pack-result" data-catalog-pack="${p.id}"><h3>${esc(p.name)} <small>${p.tier}</small></h3><div class="catalog-items">${p.contents.map(l=>`<span title="${esc(catalog.items[l.id].name)}">${image(l.id)}<small>${esc(l.quantity)}</small></span>`).join('')}</div><p data-value></p><details><summary>Contents &amp; calculation</summary><div data-breakdown></div><label>Gold-bar cost <input data-cost="${p.id}" type="number" min="1" inputmode="decimal" value="${esc(saved.costs[p.id]??'')}" placeholder="Not verified"></label></details></article>`).join('')}</div><details class="compact-help"><summary>Item gem-price reference</summary><p>Diamonds count at face value. Other items need a regular gem-shop price. Z Points, alliance currency and discounted offers are not interchangeable with gems.</p><p><a href="https://lastzguides.com/trade-hubs.html" target="_blank" rel="noopener">Season 3 Trade Hub reference</a>: five 1-hour construction speedups cost 500 gems at the regular price (100 per hour). This season-specific price is not applied to every shop automatically.</p><div class="catalog-price-list">${Object.entries(catalog.items).map(([id,item])=>`<label>${image(id)}<span>${esc(item.name)}<small>${item.gems!=null?`${fmt(item.gems)} gems per item`:'Regular gems per item · unverified'}</small></span>${item.gems==null?`<input type="number" min="0" step="any" inputmode="decimal" data-price="${id}" value="${esc(saved.prices[id]??'')}" placeholder="Unknown">`:''}</label>`).join('')}</div></details><p class="hint"><a href="${catalog.source}" target="_blank" rel="noopener">Official pack source</a>. Packs and availability can change. Tier identifies a store variant, not its gold-bar price. All contents must be priced before a pack can be ranked. Your checked prices stay on this device.</p>`;
 function update(){const values=catalog.packs.map(p=>({...p,...catalogValue(p,saved.prices,saved.costs[p.id])}));const best=Math.max(...values.filter(p=>p.complete).map(p=>p.ratio));for(const p of values){const node=container.querySelector(`[data-catalog-pack="${p.id}"]`);node.querySelector('[data-value]').textContent=p.complete?`${fmt(p.gems)} gems · ${fmt(p.ratio)} gems / gold bar${p.ratio===best?' · Best verified value':''}`:`${fmt(p.gems)} known gems · ${p.missing} unpriced items${Number(saved.costs[p.id])>0?'':' · cost needed'}`;node.querySelector('[data-breakdown]').innerHTML=p.lines.map(l=>`<p>${esc(l.quantity)} × ${esc(catalog.items[l.id].name)} → ${l.value===null?'gem price unknown':fmt(l.value)+' gems'}</p>`).join('');}}
 container.oninput=e=>{if(e.target.dataset.price)saved.prices[e.target.dataset.price]=e.target.value;else if(e.target.dataset.cost)saved.costs[e.target.dataset.cost]=e.target.value;else return;try{localStorage.setItem('lastz-pack-catalog',JSON.stringify(saved));}catch{}update();};update();
}

